# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CityWave' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CityWave

  rn_path = '../node_modules/react-native'
  rn_maps_path  = '../node_modules/react-native-maps'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'ART',
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # very important to have, unless you removed React dependencies for Libraries
    # and you rely on Cocoapods to manage it
    targets_to_ignore = %w(React yoga)
    if targets_to_ignore.include? target.name
        target.remove_from_project
    end
  end
end